### ISSUE TITLE
How to send in macOS in iTerm2?

### ISSUE THREAD

**Issue by eccstartup** [gnachman/gptline#4]
<img width="1115" alt="image" src="https://github.com/gnachman/gptline/assets/2290484/fa9d0905-d8cf-4571-a56e-a14586d91f7b">
What is `M-<Enter>`? In my situation, it just maximizes the window.

**Comment by gnachman** [comment]
Meta-return, which is typically the Option key. You'll need to configure option to send Esc+:

<img width="1128" alt="Screenshot 2023-10-16 at 4 33 06 PM 1" src="https://github.com/gnachman/gptline/assets/427546/db503411-cd19-4c73-a248-d16b448b811f">

You can also move the cursor to the end and press control-D.
